### PR TITLE
Fix Linux and CentOS compilation

### LINKED ISSUE #32: failed to build due qt5
I am using one of the latest Linux Mint (Ubuntu based)
it fails to build while looking for qt libraries:

> Package QtGui was not found in the pkg-config search path.
> Perhaps you should add the directory containing `QtGui.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'QtGui' found
> ...
> OSError: 'pkg-config QtGui QtWidgets QtCore QtOpenGL QtXml QtXmlPatterns QtNetwork --libs --cflags' exited 1:
> ...

It looks like it is expecting the 5 in the Qt5* library names.
For instance, if I run in command line:
> pkg-config Qt5Gui Qt5Widgets Qt5Core Qt5OpenGL Qt5Xml Qt5XmlPatterns Qt5Network --libs --cflags

it returns OK.

### LINKED ISSUE #39: CentOS 7: pthread_setname_np issue
src/libcore/thread.cpp: In static member function ‘static void mitsuba::Thread::initializeOpenMP(size_t)’:
src/libcore/thread.cpp:637:53: error: invalid conversion from ‘const char*’ to ‘pthread_t {aka long unsigned int}’ [-fpermissive]
                 pthread_setname_np(threadName.c_str());
                                                     ^
src/libcore/thread.cpp:637:54: error: too few arguments to function ‘int pthread_setname_np(pthread_t, const char*)’
                 pthread_setname_np(threadName.c_str());

I modify pthread_setname_np(threadName.c_str());  to pthread_setname_np((pthread_self(),threadName.c_str());  It's OK.

### PR DESCRIPTION
**Pull request by amyspark**
- Map between Qt package names and pkg-config names; fixes #32
 - thread.cpp: pthreads needed an additional parameter, my bad; fixes #39

### CODE REVIEW

**Comment by wjakob** [comment]
I think the current code is correct for OSX and incorrect for Linux. They have different function signatures, which is a bit confusing.

**Comment by chaosink** [comment]
This works on Linux Mint 18.2. Thanks for @amyspark.

**Comment by chaosink** [comment]
This works on Linux Mint 18.2. But still can't complete the compilation. Seems a lot work and tests to do...

**Comment by amyspark** [comment]
I've got it working on both MacOS and Linux Mint/Ubuntu (see https://github.com/amyspark/mitsuba/commits/add-license-and-readme). @chaosink, what errors did you get?

**Comment by chaosink** [comment]
Why not add `,'-std=c++11', '-fPIC'` to `CXXFLAGS` also in `config-linux-gcc.py`. :smile: Seems only the debug version is tested, which is so slow.

Yes. This works on Linux Mint 18.2 for both debug and release version.

Thanks for @amyspark .

**Comment by chaosink** [comment]
Maybe all the binaries can be put together, just like the cmake did in 0.5.0 version.

**Comment by amyspark** [comment]
@chaosink 🤦‍♀️, I forgot to do it in #36... fix incoming.

**Comment by diiigle** [comment]
confirmed: fixes compilation on Ubuntu (WSL).

**Comment by OstZ** [comment]
why not merge?
